schema:
  - http://localhost:4000/graphql
documents:
  - 'src/api/**/*.graphql'
generates:
  src/api/__generated__/graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
    config:
      withRefetchFn: true